export interface PanchayathEntry {
  name: string;
  district: string;
  pincode: string;
  type: "grama" | "municipality" | "corporation";
}

export const KERALA_PANCHAYATHS: PanchayathEntry[] = [
  // ─── Thiruvananthapuram ───────────────────────────────────────────────────
  { name: "Thiruvananthapuram", district: "Thiruvananthapuram", pincode: "695001", type: "corporation" },
  { name: "Neyyattinkara",      district: "Thiruvananthapuram", pincode: "695121", type: "municipality" },
  { name: "Attingal",           district: "Thiruvananthapuram", pincode: "695101", type: "municipality" },
  { name: "Nedumangad",         district: "Thiruvananthapuram", pincode: "695541", type: "municipality" },
  { name: "Varkala",            district: "Thiruvananthapuram", pincode: "695141", type: "municipality" },
  { name: "Kazhakoottam",       district: "Thiruvananthapuram", pincode: "695582", type: "grama" },
  { name: "Balaramapuram",      district: "Thiruvananthapuram", pincode: "695501", type: "grama" },
  { name: "Parassala",          district: "Thiruvananthapuram", pincode: "695502", type: "grama" },
  { name: "Pothencode",         district: "Thiruvananthapuram", pincode: "695584", type: "grama" },
  { name: "Vellanad",           district: "Thiruvananthapuram", pincode: "695543", type: "grama" },
  { name: "Kallambalam",        district: "Thiruvananthapuram", pincode: "695605", type: "grama" },
  { name: "Chirayinkeezhu",     district: "Thiruvananthapuram", pincode: "695304", type: "grama" },
  { name: "Vithura",            district: "Thiruvananthapuram", pincode: "695551", type: "grama" },
  { name: "Aruvikkara",         district: "Thiruvananthapuram", pincode: "695543", type: "grama" },
  { name: "Karakulam",          district: "Thiruvananthapuram", pincode: "695564", type: "grama" },
  { name: "Andoorkonam",        district: "Thiruvananthapuram", pincode: "695572", type: "grama" },
  { name: "Maranalloor",        district: "Thiruvananthapuram", pincode: "695615", type: "grama" },
  { name: "Pallichal",          district: "Thiruvananthapuram", pincode: "695020", type: "grama" },
  { name: "Tholicode",          district: "Thiruvananthapuram", pincode: "695573", type: "grama" },
  { name: "Perumkadavila",      district: "Thiruvananthapuram", pincode: "695124", type: "grama" },

  // ─── Kollam ───────────────────────────────────────────────────────────────
  { name: "Kollam",             district: "Kollam", pincode: "691001", type: "corporation" },
  { name: "Punalur",            district: "Kollam", pincode: "691305", type: "municipality" },
  { name: "Karunagappally",     district: "Kollam", pincode: "690518", type: "municipality" },
  { name: "Kottarakkara",       district: "Kollam", pincode: "691506", type: "municipality" },
  { name: "Kundara",            district: "Kollam", pincode: "691501", type: "municipality" },
  { name: "Chavara",            district: "Kollam", pincode: "691583", type: "grama" },
  { name: "Kureepuzha",         district: "Kollam", pincode: "691013", type: "grama" },
  { name: "Mynagappally",       district: "Kollam", pincode: "690503", type: "grama" },
  { name: "Oachira",            district: "Kollam", pincode: "690526", type: "grama" },
  { name: "Kulasekharapuram",   district: "Kollam", pincode: "691542", type: "grama" },
  { name: "Pathanapuram",       district: "Kollam", pincode: "689695", type: "grama" },
  { name: "Chadayamangalam",    district: "Kollam", pincode: "691536", type: "grama" },
  { name: "Anchal",             district: "Kollam", pincode: "691306", type: "grama" },
  { name: "Perinad",            district: "Kollam", pincode: "691601", type: "grama" },
  { name: "Paravur",            district: "Kollam", pincode: "691301", type: "municipality" },

  // ─── Pathanamthitta ───────────────────────────────────────────────────────
  { name: "Pathanamthitta",     district: "Pathanamthitta", pincode: "689645", type: "municipality" },
  { name: "Thiruvalla",         district: "Pathanamthitta", pincode: "689101", type: "municipality" },
  { name: "Adoor",              district: "Pathanamthitta", pincode: "691523", type: "municipality" },
  { name: "Pandalam",           district: "Pathanamthitta", pincode: "689501", type: "municipality" },
  { name: "Ranni",              district: "Pathanamthitta", pincode: "689673", type: "grama" },
  { name: "Kozhencherry",       district: "Pathanamthitta", pincode: "689641", type: "grama" },
  { name: "Aranmula",           district: "Pathanamthitta", pincode: "689533", type: "grama" },
  { name: "Konni",              district: "Pathanamthitta", pincode: "689691", type: "grama" },
  { name: "Mallappally",        district: "Pathanamthitta", pincode: "689585", type: "grama" },
  { name: "Kadapra",            district: "Pathanamthitta", pincode: "689643", type: "grama" },
  { name: "Ezhamkulam",         district: "Pathanamthitta", pincode: "689505", type: "grama" },

  // ─── Alappuzha ────────────────────────────────────────────────────────────
  { name: "Alappuzha",          district: "Alappuzha", pincode: "688001", type: "municipality" },
  { name: "Cherthala",          district: "Alappuzha", pincode: "688524", type: "municipality" },
  { name: "Kayamkulam",         district: "Alappuzha", pincode: "690502", type: "municipality" },
  { name: "Mavelikkara",        district: "Alappuzha", pincode: "690101", type: "municipality" },
  { name: "Chengannur",         district: "Alappuzha", pincode: "689121", type: "municipality" },
  { name: "Haripad",            district: "Alappuzha", pincode: "690514", type: "municipality" },
  { name: "Ambalapuzha",        district: "Alappuzha", pincode: "688561", type: "grama" },
  { name: "Kuttanad",           district: "Alappuzha", pincode: "688541", type: "grama" },
  { name: "Budhanoor",          district: "Alappuzha", pincode: "689122", type: "grama" },
  { name: "Veeyapuram",         district: "Alappuzha", pincode: "689108", type: "grama" },
  { name: "Arookutty",          district: "Alappuzha", pincode: "688535", type: "grama" },
  { name: "Mararikulam",        district: "Alappuzha", pincode: "688523", type: "grama" },

  // ─── Kottayam ─────────────────────────────────────────────────────────────
  { name: "Kottayam",           district: "Kottayam", pincode: "686001", type: "municipality" },
  { name: "Pala",               district: "Kottayam", pincode: "686575", type: "municipality" },
  { name: "Changanacherry",     district: "Kottayam", pincode: "686101", type: "municipality" },
  { name: "Vaikom",             district: "Kottayam", pincode: "686141", type: "municipality" },
  { name: "Ettumanoor",         district: "Kottayam", pincode: "686631", type: "municipality" },
  { name: "Erattupetta",        district: "Kottayam", pincode: "686121", type: "municipality" },
  { name: "Kanjirappally",      district: "Kottayam", pincode: "686507", type: "grama" },
  { name: "Mundakayam",         district: "Kottayam", pincode: "686513", type: "grama" },
  { name: "Kadanad",            district: "Kottayam", pincode: "686583", type: "grama" },
  { name: "Thiruvarppu",        district: "Kottayam", pincode: "686020", type: "grama" },
  { name: "Karukachal",         district: "Kottayam", pincode: "686540", type: "grama" },
  { name: "Kumarakom",          district: "Kottayam", pincode: "686563", type: "grama" },
  { name: "Marangattupilly",    district: "Kottayam", pincode: "686544", type: "grama" },

  // ─── Idukki ───────────────────────────────────────────────────────────────
  { name: "Thodupuzha",         district: "Idukki", pincode: "685584", type: "municipality" },
  { name: "Munnar",             district: "Idukki", pincode: "685612", type: "grama" },
  { name: "Adimali",            district: "Idukki", pincode: "685561", type: "grama" },
  { name: "Devikulam",          district: "Idukki", pincode: "685613", type: "grama" },
  { name: "Nedumkandam",        district: "Idukki", pincode: "685553", type: "grama" },
  { name: "Kattappana",         district: "Idukki", pincode: "685508", type: "municipality" },
  { name: "Peermade",           district: "Idukki", pincode: "685531", type: "grama" },
  { name: "Kumily",             district: "Idukki", pincode: "685509", type: "grama" },
  { name: "Udumbanchola",       district: "Idukki", pincode: "685551", type: "grama" },
  { name: "Azhutha",            district: "Idukki", pincode: "685505", type: "grama" },
  { name: "Vandanmedu",         district: "Idukki", pincode: "685533", type: "grama" },
  { name: "Rajakkad",           district: "Idukki", pincode: "685511", type: "grama" },

  // ─── Ernakulam ────────────────────────────────────────────────────────────
  { name: "Kochi",              district: "Ernakulam", pincode: "682001", type: "corporation" },
  { name: "Thrippunithura",     district: "Ernakulam", pincode: "682301", type: "municipality" },
  { name: "Aluva",              district: "Ernakulam", pincode: "683101", type: "municipality" },
  { name: "Angamaly",           district: "Ernakulam", pincode: "683572", type: "municipality" },
  { name: "Perumbavoor",        district: "Ernakulam", pincode: "683542", type: "municipality" },
  { name: "Muvattupuzha",       district: "Ernakulam", pincode: "686661", type: "municipality" },
  { name: "North Paravur",      district: "Ernakulam", pincode: "683513", type: "municipality" },
  { name: "Kothamangalam",      district: "Ernakulam", pincode: "686691", type: "municipality" },
  { name: "Kolenchery",         district: "Ernakulam", pincode: "682311", type: "grama" },
  { name: "Piravom",            district: "Ernakulam", pincode: "686664", type: "grama" },
  { name: "Cheranalloor",       district: "Ernakulam", pincode: "682034", type: "grama" },
  { name: "Kakkanad",           district: "Ernakulam", pincode: "682030", type: "grama" },
  { name: "Chottanikkara",      district: "Ernakulam", pincode: "682312", type: "grama" },
  { name: "Kuruppampady",       district: "Ernakulam", pincode: "683545", type: "grama" },
  { name: "Kunnathunadu",       district: "Ernakulam", pincode: "682311", type: "grama" },
  { name: "Edathala",           district: "Ernakulam", pincode: "683561", type: "grama" },
  { name: "Kochi South",        district: "Ernakulam", pincode: "682016", type: "grama" },
  { name: "Keezhmad",           district: "Ernakulam", pincode: "683541", type: "grama" },
  { name: "Mulanthuruthy",      district: "Ernakulam", pincode: "682314", type: "grama" },

  // ─── Thrissur ─────────────────────────────────────────────────────────────
  { name: "Thrissur",           district: "Thrissur", pincode: "680001", type: "corporation" },
  { name: "Chalakudy",          district: "Thrissur", pincode: "680307", type: "municipality" },
  { name: "Irinjalakuda",       district: "Thrissur", pincode: "680121", type: "municipality" },
  { name: "Kodungallur",        district: "Thrissur", pincode: "680664", type: "municipality" },
  { name: "Guruvayur",          district: "Thrissur", pincode: "680101", type: "municipality" },
  { name: "Kunnamkulam",        district: "Thrissur", pincode: "680503", type: "municipality" },
  { name: "Wadakkanchery",      district: "Thrissur", pincode: "680623", type: "municipality" },
  { name: "Chavakkad",          district: "Thrissur", pincode: "680505", type: "municipality" },
  { name: "Mala",               district: "Thrissur", pincode: "680732", type: "grama" },
  { name: "Ollur",              district: "Thrissur", pincode: "680306", type: "grama" },
  { name: "Anthiyur",           district: "Thrissur", pincode: "680681", type: "grama" },
  { name: "Velur",              district: "Thrissur", pincode: "680601", type: "grama" },
  { name: "Engandiyur",         district: "Thrissur", pincode: "680616", type: "grama" },
  { name: "Paralam",            district: "Thrissur", pincode: "680563", type: "grama" },
  { name: "Pavaratty",          district: "Thrissur", pincode: "680507", type: "grama" },
  { name: "Cherpu",             district: "Thrissur", pincode: "680561", type: "grama" },
  { name: "Thiruvilwamala",     district: "Thrissur", pincode: "680588", type: "grama" },
  { name: "Mullurkkara",        district: "Thrissur", pincode: "680581", type: "grama" },
  { name: "Nenmanikkara",       district: "Thrissur", pincode: "680545", type: "grama" },
  { name: "Thrithala",          district: "Thrissur", pincode: "679531", type: "grama" },

  // ─── Palakkad ─────────────────────────────────────────────────────────────
  { name: "Palakkad",           district: "Palakkad", pincode: "678001", type: "municipality" },
  { name: "Ottapalam",          district: "Palakkad", pincode: "679101", type: "municipality" },
  { name: "Shoranur",           district: "Palakkad", pincode: "679121", type: "municipality" },
  { name: "Mannarkkad",         district: "Palakkad", pincode: "678582", type: "municipality" },
  { name: "Chittur",            district: "Palakkad", pincode: "678101", type: "municipality" },
  { name: "Pattambi",           district: "Palakkad", pincode: "679303", type: "municipality" },
  { name: "Alathur",            district: "Palakkad", pincode: "678541", type: "municipality" },
  { name: "Nemmara",            district: "Palakkad", pincode: "678508", type: "grama" },
  { name: "Malampuzha",         district: "Palakkad", pincode: "678651", type: "grama" },
  { name: "Kozhinjampara",      district: "Palakkad", pincode: "678555", type: "grama" },
  { name: "Lakkidi",            district: "Palakkad", pincode: "678621", type: "grama" },
  { name: "Vadakarapathy",      district: "Palakkad", pincode: "679105", type: "grama" },
  { name: "Pirayiri",           district: "Palakkad", pincode: "679301", type: "grama" },
  { name: "Tharur",             district: "Palakkad", pincode: "679536", type: "grama" },
  { name: "Paruthur",           district: "Palakkad", pincode: "679303", type: "grama" },
  { name: "Sreekrishnapuram",   district: "Palakkad", pincode: "679513", type: "grama" },
  { name: "Kongad",             district: "Palakkad", pincode: "678631", type: "grama" },

  // ─── Malappuram ───────────────────────────────────────────────────────────
  { name: "Malappuram",         district: "Malappuram", pincode: "676505", type: "municipality" },
  { name: "Manjeri",            district: "Malappuram", pincode: "676121", type: "municipality" },
  { name: "Tirur",              district: "Malappuram", pincode: "676101", type: "municipality" },
  { name: "Ponnani",            district: "Malappuram", pincode: "679577", type: "municipality" },
  { name: "Perinthalmanna",     district: "Malappuram", pincode: "679322", type: "municipality" },
  { name: "Kottakkal",          district: "Malappuram", pincode: "676503", type: "municipality" },
  { name: "Tanur",              district: "Malappuram", pincode: "676302", type: "municipality" },
  { name: "Nilambur",           district: "Malappuram", pincode: "679329", type: "municipality" },
  { name: "Tirurrangadi",       district: "Malappuram", pincode: "676306", type: "grama" },
  { name: "Edappal",            district: "Malappuram", pincode: "679576", type: "grama" },
  { name: "Wandoor",            district: "Malappuram", pincode: "679328", type: "grama" },
  { name: "Kondotty",           district: "Malappuram", pincode: "673638", type: "grama" },
  { name: "Valanchery",         district: "Malappuram", pincode: "676552", type: "grama" },
  { name: "Chelembra",          district: "Malappuram", pincode: "673634", type: "grama" },
  { name: "Vengara",            district: "Malappuram", pincode: "676304", type: "grama" },
  { name: "Pulamanthole",       district: "Malappuram", pincode: "679323", type: "grama" },
  { name: "Munniyur",           district: "Malappuram", pincode: "676551", type: "grama" },
  { name: "Othukkungal",        district: "Malappuram", pincode: "676317", type: "grama" },
  { name: "Parappanangadi",     district: "Malappuram", pincode: "676303", type: "grama" },
  { name: "Trikkandiyur",       district: "Malappuram", pincode: "676107", type: "grama" },
  { name: "Kalpakanchery",      district: "Malappuram", pincode: "676552", type: "grama" },
  { name: "Kuruva",             district: "Malappuram", pincode: "676508", type: "grama" },
  { name: "Moothedam",          district: "Malappuram", pincode: "676507", type: "grama" },
  { name: "Vettom",             district: "Malappuram", pincode: "676501", type: "grama" },
  { name: "Irimbiliyam",        district: "Malappuram", pincode: "676508", type: "grama" },
  { name: "Marakkara",          district: "Malappuram", pincode: "673636", type: "grama" },
  { name: "Perumpadappu",       district: "Malappuram", pincode: "679579", type: "grama" },
  { name: "Kuttippuram",        district: "Malappuram", pincode: "679571", type: "grama" },
  { name: "Vazhayur",           district: "Malappuram", pincode: "676123", type: "grama" },
  { name: "Thrikkalangode",     district: "Malappuram", pincode: "676509", type: "grama" },
  { name: "Mangalam",           district: "Malappuram", pincode: "676551", type: "grama" },
  { name: "Thirunavaya",        district: "Malappuram", pincode: "676301", type: "grama" },
  { name: "Mankada",            district: "Malappuram", pincode: "679324", type: "grama" },
  { name: "Edarikode",          district: "Malappuram", pincode: "676501", type: "grama" },
  { name: "Athavanad",          district: "Malappuram", pincode: "676102", type: "grama" },
  { name: "Areacode",           district: "Malappuram", pincode: "673639", type: "grama" },
  { name: "Kalikavu",           district: "Malappuram", pincode: "679330", type: "grama" },
  { name: "Valavannur",         district: "Malappuram", pincode: "676562", type: "grama" },
  { name: "Mampad",             district: "Malappuram", pincode: "676542", type: "grama" },
  { name: "Pandikkad",          district: "Malappuram", pincode: "676521", type: "grama" },

  // ─── Kozhikode ────────────────────────────────────────────────────────────
  { name: "Kozhikode",          district: "Kozhikode", pincode: "673001", type: "corporation" },
  { name: "Vadakara",           district: "Kozhikode", pincode: "673101", type: "municipality" },
  { name: "Koyilandy",          district: "Kozhikode", pincode: "673305", type: "municipality" },
  { name: "Feroke",             district: "Kozhikode", pincode: "673631", type: "municipality" },
  { name: "Ramanattukara",      district: "Kozhikode", pincode: "673633", type: "municipality" },
  { name: "Balussery",          district: "Kozhikode", pincode: "673612", type: "grama" },
  { name: "Perambra",           district: "Kozhikode", pincode: "673525", type: "grama" },
  { name: "Kuttiady",           district: "Kozhikode", pincode: "673508", type: "grama" },
  { name: "Thamarassery",       district: "Kozhikode", pincode: "673573", type: "grama" },
  { name: "Mukkam",             district: "Kozhikode", pincode: "673602", type: "grama" },
  { name: "Koduvally",          district: "Kozhikode", pincode: "673572", type: "grama" },
  { name: "Thiruvambady",       district: "Kozhikode", pincode: "673603", type: "grama" },
  { name: "Quilandy",           district: "Kozhikode", pincode: "673305", type: "grama" },
  { name: "Kadalundi",          district: "Kozhikode", pincode: "673306", type: "grama" },
  { name: "Olavanna",           district: "Kozhikode", pincode: "673019", type: "grama" },
  { name: "Narikkuni",          district: "Kozhikode", pincode: "673512", type: "grama" },
  { name: "Omassery",           district: "Kozhikode", pincode: "673582", type: "grama" },
  { name: "Kayanna",            district: "Kozhikode", pincode: "673522", type: "grama" },
  { name: "Koorachundu",        district: "Kozhikode", pincode: "673524", type: "grama" },
  { name: "Kunnummel",          district: "Kozhikode", pincode: "673612", type: "grama" },
  { name: "Chemanchery",        district: "Kozhikode", pincode: "673521", type: "grama" },
  { name: "Unnikulam",          district: "Kozhikode", pincode: "673528", type: "grama" },
  { name: "Changaroth",         district: "Kozhikode", pincode: "673529", type: "grama" },
  { name: "Nadapuram",          district: "Kozhikode", pincode: "673508", type: "grama" },
  { name: "Perumanna",          district: "Kozhikode", pincode: "673020", type: "grama" },
  { name: "Thikkodi",           district: "Kozhikode", pincode: "673308", type: "grama" },
  { name: "Atholi",             district: "Kozhikode", pincode: "673315", type: "grama" },
  { name: "Villiappally",       district: "Kozhikode", pincode: "673317", type: "grama" },
  { name: "Koodaranhi",         district: "Kozhikode", pincode: "673307", type: "grama" },

  // ─── Wayanad ──────────────────────────────────────────────────────────────
  { name: "Kalpetta",           district: "Wayanad", pincode: "673121", type: "municipality" },
  { name: "Mananthavady",       district: "Wayanad", pincode: "670645", type: "municipality" },
  { name: "Sulthan Bathery",    district: "Wayanad", pincode: "673592", type: "municipality" },
  { name: "Vythiri",            district: "Wayanad", pincode: "673576", type: "grama" },
  { name: "Ambalavayal",        district: "Wayanad", pincode: "673593", type: "grama" },
  { name: "Panamaram",          district: "Wayanad", pincode: "670721", type: "grama" },
  { name: "Meenangadi",         district: "Wayanad", pincode: "673591", type: "grama" },
  { name: "Nenmeni",            district: "Wayanad", pincode: "673524", type: "grama" },
  { name: "Poothadi",           district: "Wayanad", pincode: "673577", type: "grama" },
  { name: "Muttil",             district: "Wayanad", pincode: "673122", type: "grama" },
  { name: "Kaniyambetta",       district: "Wayanad", pincode: "673124", type: "grama" },
  { name: "Thondernad",         district: "Wayanad", pincode: "670646", type: "grama" },

  // ─── Kannur ───────────────────────────────────────────────────────────────
  { name: "Kannur",             district: "Kannur", pincode: "670001", type: "corporation" },
  { name: "Thalassery",         district: "Kannur", pincode: "670101", type: "municipality" },
  { name: "Payyannur",          district: "Kannur", pincode: "670307", type: "municipality" },
  { name: "Iritty",             district: "Kannur", pincode: "670703", type: "municipality" },
  { name: "Mattannur",          district: "Kannur", pincode: "670702", type: "municipality" },
  { name: "Thaliparamba",       district: "Kannur", pincode: "670141", type: "municipality" },
  { name: "Kuthuparamba",       district: "Kannur", pincode: "670643", type: "municipality" },
  { name: "Panoor",             district: "Kannur", pincode: "670692", type: "grama" },
  { name: "Edakkad",            district: "Kannur", pincode: "670007", type: "grama" },
  { name: "Sreekandapuram",     district: "Kannur", pincode: "670631", type: "grama" },
  { name: "Peravoor",           district: "Kannur", pincode: "670673", type: "grama" },
  { name: "Aralam",             district: "Kannur", pincode: "670704", type: "grama" },
  { name: "Chapparapadavu",     district: "Kannur", pincode: "670741", type: "grama" },
  { name: "Cherupuzha",         district: "Kannur", pincode: "670508", type: "grama" },
  { name: "Chirakkal",          district: "Kannur", pincode: "670011", type: "grama" },
  { name: "Kalliasseri",        district: "Kannur", pincode: "670562", type: "grama" },
  { name: "Azhikode",           district: "Kannur", pincode: "670009", type: "grama" },
  { name: "Payyavoor",          district: "Kannur", pincode: "670308", type: "grama" },
  { name: "Koothuparamba",      district: "Kannur", pincode: "670643", type: "grama" },

  // ─── Kasaragod ────────────────────────────────────────────────────────────
  { name: "Kasaragod",          district: "Kasaragod", pincode: "671121", type: "municipality" },
  { name: "Kanhangad",          district: "Kasaragod", pincode: "671315", type: "municipality" },
  { name: "Manjeshwar",         district: "Kasaragod", pincode: "671323", type: "municipality" },
  { name: "Hosdurg",            district: "Kasaragod", pincode: "671316", type: "grama" },
  { name: "Nileshwar",          district: "Kasaragod", pincode: "671314", type: "grama" },
  { name: "Cheruvathur",        district: "Kasaragod", pincode: "671313", type: "grama" },
  { name: "Bekal",              district: "Kasaragod", pincode: "671318", type: "grama" },
  { name: "Uduma",              district: "Kasaragod", pincode: "671318", type: "grama" },
  { name: "Vorkady",            district: "Kasaragod", pincode: "671321", type: "grama" },
  { name: "Cheemeni",           district: "Kasaragod", pincode: "671313", type: "grama" },
  { name: "Karadka",            district: "Kasaragod", pincode: "671541", type: "grama" },
  { name: "Puthige",            district: "Kasaragod", pincode: "671531", type: "grama" },
  { name: "Perdala",            district: "Kasaragod", pincode: "671541", type: "grama" },
  { name: "Trikarpur",          district: "Kasaragod", pincode: "671310", type: "grama" },
  { name: "Mulleria",           district: "Kasaragod", pincode: "671542", type: "grama" },
];

export const STATE = "Kerala";

export function searchPanchayaths(query: string, limit = 8): PanchayathEntry[] {
  if (!query.trim()) return [];
  const q = query.toLowerCase();
  return KERALA_PANCHAYATHS
    .filter((p) => p.name.toLowerCase().includes(q) || p.district.toLowerCase().includes(q))
    .slice(0, limit);
}

export function findPanchayath(name: string): PanchayathEntry | undefined {
  return KERALA_PANCHAYATHS.find(
    (p) => p.name.toLowerCase() === name.toLowerCase()
  );
}
